/*
 * E2PROM_config.c
 *
 *  Created on: Jan 2, 2025
 *      Author: Ahmedmohamed
 */




#include "E2PROM_config.h"

/* EEPROM configuration instance (this would typically be generated by an AUTOSAR tool) */
const Eeprom_ConfigType Eeprom_Config = {

    .baseAddress = 0x1000,  // Example base address (change as needed)
    .maxSize = 0x4000      // Example max size (change as needed)
};


